///level_load_init()
global.createX=0;
global.createY=0;
global.createZ=0;
global.createX1=0;
global.createY1=0;
global.createX2=0;
global.createY2=0;
global.createHeight=0;
global.createId=0;
global.createFloorZ=0;
global.createFloorHeight=0;
global.createCeilingZ=0;
global.createCeilingHeight=0;
global.isTrigger=0;
global.triggerId=0;
